### ISSUE TITLE
[USB] Photon/P1/Electron should be able to wake up a sleeping USB host

### ISSUE THREAD

**Issue by avtolstoy** [particle-iot/device-os#1293]
## Feature/Enhancement Request

As described in title. Original thread on community forums: https://community.particle.io/t/hid-keyboard-on-photon-waking-a-connected-device/29387/3

**Comment by yellowjaguar5** [comment]
update?

**Comment by ethanpierce** [comment]
We don't need to have USB Suspend implemented in the DeviceOS in order to use HID commands to wake up a host machine. USB Suspend is typically used to enable a lower power state for the usb device thats connected. I'm confident that USB suspend is not required in order for @yellowjaguar5 to accomplish the original use case.
