### ISSUE TITLE
Delay between time when Photon actually comes offline and time when Particle cloud publishes "offline" event

### ISSUE THREAD

**Issue by SergeyKiselev1995** [particle-iot/device-os#1347]
### Expected Behavior

When Photon device is disconnected from power supply particle cloud triggers it in short time and publishes "device offline" event so webhooks can handle this event

### Observed Behavior

When Photon is unplugged "device offline" event is published only in 15-20 minutes after actual "disconnect" event

### Steps to Reproduce

This behavior can be reproduced by disconnecting Photon device form power supply

**Comment by m-mcgowan** [comment]
Thanks for the issue report. Could you please tell us more about the setup you have:
- what version of system firmware is running on your device.  [how to](https://community.particle.io/t/determining-the-version-of-system-firmware-on-a-photon-p1/13324) 
- how reproducible is this? does it happen every time?
- anything unusual about your system firmware, e.g. are you running UDP rather than TCP?

In principle, the cloud expects to hear from devices at regular intervals and will disconnect the device after 15 seconds.

**Comment by SergeyKiselev1995** [comment]
Hi. Thank you for response.

- Firmware version is 0.6.2
- I've tested 10 times and in 9 of them delay was 10 and more minutes. In one case delay was just 1 minute.
- There is nothing unusual in system firmware.

**Comment by JamesHagerman** [comment]
The behavior around these events has been updated for Photons. This should no longer be an issue.
