### ISSUE TITLE
Cellular.resetDataUsage()/Cellular.setDataUsage() doesn't set the internal SARA modem counters

### ISSUE THREAD

**Issue by kubark42** [particle-iot/device-os#1552]
### Expected Behavior

When I reset the modem counters, they should reset internally in the SARA module, not just for one boot cycle in the STM32.

### Observed Behavior

`resetDataUsage()` resets the onboard Particle counter, but after a reboot the original number returns.

### References

Example 5.5: https://www.u-blox.com/sites/default/files/AT-CommandsExamples_AppNote_%28UBX-13001820%29.pdf hints that the right command to use is `UGCNTSET`. However, this AT command does not show up in the [Particle firmware codebase](https://github.com/particle-iot/firmware/search?q=UGCNTSET&unscoped_q=UGCNTSET).

https://github.com/particle-iot/firmware/blob/b20d009711f16a75003d4310a037ef2f14c647ed/hal/src/electron/cellular_hal.cpp#L249 seems to show the internal data structure being altered, but not being subsequently set.

Since the code shows that the setting and resetting use the same logic path (although different numbers), then `setDataUsage()` must have a similar problem.

---

**Comment by technobly** [comment]
@kubark42 this is by design due to a bug in the U260/U270 modem firmware.

Please see the notes here: https://docs.particle.io/reference/firmware/electron/#getdatausage-

If you have the G350 modem you can run the AT command you referenced with Cellular.command() to effectively reset the data usage in the modem.
