### ISSUE TITLE
Cant get wifi credentials in timer

### ISSUE THREAD

**Issue by angelo0000** [particle-iot/device-os#1853]
### Expected Behavior

Should be able to get the wifi creds and not crash

### Observed Behavior

Particle Photon SOS 13 (stack overflow) [Technobly: edited error code]

### Steps to Reproduce

Particle Photon running OS 1.2.1.  The sample test app calls a function that will print the GOT HERE to the serial logger.  When the timer tries to run the same function the Photon will hard fault.

### Test App

```c
SYSTEM_MODE(SEMI_AUTOMATIC);
SYSTEM_THREAD(ENABLED);


SerialLogHandler logHandler;

Timer credsTest(10000, tryToGetCreds);

void tryToGetCreds(){
    WiFiAccessPoint credAP[1];
    int found = WiFi.getCredentials(credAP, 1);
    Log.info("GOT HERE");
}

void setup(){
    Serial.begin(9600);
    waitFor(Serial.isConnected, 10000);
    delay(2000);
    
    tryToGetCreds();
    credsTest.start();
}

void loop(){
}

```

### References

Links to the Community, Docs, Other Issues, etc..

---

**Comment by technobly** [comment]
I just tested this and found it to be an SOS 13 (stack overflow), not SOS 1 (hard fault).  When looking at the blinking RED LED, there is a SOS pattern ...---... followed by a number of blinks.  Those blinks need to be counted and reported to better understand the issue: https://docs.particle.io/tutorials/device-os/led/photon/#red-flash-sos

In this case, you should probably not be doing so much work in your timer which is causing too much stack allocation, and potentially offloading the work to the loop() with a flag like this:

```cpp
SYSTEM_MODE(SEMI_AUTOMATIC);
SYSTEM_THREAD(ENABLED);

bool timerCalled = false;

SerialLogHandler logHandler;

Timer credsTest(10000, tryToGetCreds);

void tryToGetCreds(){
    Log.info("TIMER CALLED");
    timerCalled = true;
}

void setup(){
    Serial.begin(9600);
    waitFor(Serial.isConnected, 10000);
    delay(2000);
    
    tryToGetCreds();
    credsTest.start();
}

void loop(){
    if (timerCalled) {
        timerCalled = false;
        WiFiAccessPoint credAP[1];
        int found = WiFi.getCredentials(credAP, 1);
        Log.info("found: %d", found);
    }
}
```

I will close this issue since I verified your findings and provided a tested solution above.  If you feel it is not satisfactory, please discuss and we can re-open the issue.
