### ISSUE TITLE
Upgrade CC3000 Host Driver to 1.14

### ISSUE THREAD

**Issue by towynlin** [particle-iot/device-os#331]
http://processors.wiki.ti.com/index.php/CC3000_Release_Notes
Must upgrade patch programmer simultaneously.

**Comment by m-mcgowan** [comment]
The service pack has been available at https://github.com/spark/cc3000-patch-programmer/tree/ti-patch-1.14 since November, and the host driver at https://github.com/spark/firmware/tree/feature/hal-cc3000-update.

Need to verify that we can use the lasted host driver with older service packs on the cc3000, so that the host driver can be merged into the current codebase.
